# Rule W004 - Remove unnecessary loop vars
---
- name: Example playbook
  hosts: all
  tasks:
    - name: A task with unnecessary loop variable
      ansible.builtin.debug:
        msg: "{{ item.msg }}"
